### ISSUE TITLE
Allow every() method to set the padding value with optional argument

### ISSUE THREAD

**Issue by tmhglnd** [tmhglnd/total-serialism#12]
The `every()` method only appends 0's currently. Would be useful to have that value be optional to change with an argument.

**Comment by zarghamkhandev** [comment]
I am looking forward to contribute to some open source projects. Is this something I can work on ?

**Comment by ToledOmer** [comment]
Hi I just tried to fix it, I hope I understood what you meant, feel free to correct me and ask me for more :)

**Comment by tmhglnd** [comment]
Just had a look at your code, Looks good! But I would prefer the padding value to be the last argument: 

```js
every(array, bars, div, shift, padding-value)
``` 

In this way it doesn't break code that don't have the padding value set but do use the shift. If you like you can also add a test for the extra added argument and update the documentation for the every function in the transform-methods.md. In any case thank you and please make a pull request so I can merge it.

**Comment by tmhglnd** [comment]
Fixed with 508f96c2ebd389f5b0916a1a40f1131fe9f36550
