### ISSUE TITLE
Build this for importing with a script tag 

### ISSUE THREAD

**Issue by tatecarson** [tmhglnd/total-serialism#2]
Hello, 

Nice looking library. I was wondering if you could build a bundled version of this that could be used on codepen for teaching purposes. [This](https://unpkg.com/total-serialism@1.6.0/index.js) would usually work but I realized that's just an access point to the other files.

**Comment by tmhglnd** [comment]
Good idea! Not sure when I will have the time to get into it though, but maybe someone else might have time as well hopefully!

**Comment by tatecarson** [comment]
I have been trying to get it to work with out the script tag, with parcel. I keep getting errors. Maybe you have an example of how it's imported and used in one of your projects? For example, this gives me strange errors: 
https://codesandbox.io/s/total-serialism-ynf2r

Any ideas?

**Comment by tmhglnd** [comment]
I am doing exactly as you are, but am not working in the browser. So it seems that some of my JS coding may not be browser-compatible. I just did a small test with transpiling a small piece of my code to browser-compatible JS and this made the function work. So I will dive deeper into it and see how I can transpile everything quick and easily and or make a bundled version! I'll keep you posted and thanks for your message.

**Comment by tmhglnd** [comment]
I have created a bundled version for es5 under `/build/ts.es5.js`. Have to look into what will be the best way to make this available for import or the default entry point when installing the npm package for use in the browser, also not entirely sure how this will effect the projects that are currently using the non-es5 code.
